#!/usr/bin/env bash
if [[ -L $0 ]];then
    SCRIPT=`readlink -f $0`
else
    SCRIPT=$0
fi
bin=`dirname "$SCRIPT"`
export APP_DIR=`cd "$bin/"; pwd`
export PYTHONPATH=$APP_DIR:$PYTHONPATH

python -m buildfly "$@"
