#!/usr/bin/env bash
if [[ -L $0 ]];then
    if [[ $OSTYPE == darwin* ]]; then
        SCRIPT=`python -c 'import os,sys;print(os.path.realpath(sys.argv[1]))' $0`
    else
        SCRIPT=`readlink -f $0`
    fi
else
    SCRIPT=$0
fi
bin=`dirname "$SCRIPT"`
export APP_DIR=`cd "$bin/"; pwd`
export PYTHONPATH=$APP_DIR:$PYTHONPATH

python -m buildfly "$@"
